# Generated by Django 3.0.8 on 2020-07-10 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aoc2016', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microchip',
            name='botHolding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aoc2016.BalanceBot'),
        ),
        migrations.AlterField(
            model_name='output',
            name='chip1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aoc2016.Microchip'),
        ),
    ]
